$ErrorActionPreference = 'Stop'
. "$PSScriptRoot/TestHelpers.ps1"

$modifiers = Get-TestContent 'Data\Akane_Modifiers.sql'
$gameplay = Get-TestContent 'Scripts\Akane_Gameplay.lua'
$failures = New-FailureList

Expect-Match $modifiers 'AKANE_CITY_STAGE_LALALAI_CULTURE_BONUS' $failures 'Stage performance should define a LALALAI culture adjacency bonus.'
Expect-Match $modifiers 'AKANE_CITY_STAGE_LALALAI_GOLD_BONUS' $failures 'Stage performance should define a LALALAI gold adjacency bonus.'
Expect-Match $modifiers 'AKANE_CITY_STAGE_CAMPUS_DOUBLE_ADJACENCY' $failures 'Stage performance should double Campus adjacency.'
Expect-Match $modifiers 'AKANE_CITY_STAGE_COMMERCIAL_DOUBLE_ADJACENCY' $failures 'Stage performance should double Commercial Hub adjacency.'
Expect-Match $modifiers 'AKANE_CITY_STAGE_HARBOR_DOUBLE_ADJACENCY' $failures 'Stage performance should double Harbor adjacency.'
Expect-Match $modifiers 'AKANE_CITY_STAGE_ENCAMPMENT_DOUBLE_ADJACENCY' $failures 'Stage performance should double Encampment adjacency.'
Expect-Match $modifiers 'AKANE_CITY_STAGE_INDUSTRIAL_ZONE_DOUBLE_ADJACENCY' $failures 'Stage performance should double Industrial Zone adjacency.'
Expect-Match $modifiers 'AKANE_CITY_STAGE_HOLY_SITE_DOUBLE_ADJACENCY' $failures 'Stage performance should double Holy Site adjacency.'
Expect-Match $modifiers 'AKANE_CITY_STAGE_ENTERTAINMENT_COMPLEX_DOUBLE_ADJACENCY' $failures 'Stage performance should double Entertainment Complex adjacency.'
Expect-Match $modifiers 'AKANE_CITY_STAGE_WATER_PARK_DOUBLE_ADJACENCY' $failures 'Stage performance should double Water Park adjacency.'
Expect-Match $modifiers "\('AKANE_CITY_STAGE_LALALAI_CULTURE_BONUS', 'MODIFIER_CITY_DISTRICTS_ADJUST_YIELD_MODIFIER', 'DISTRICT_IS_LALALAI'\)" $failures 'Stage performance should use the official city-district yield modifier for LALALAI culture.'
Expect-Match $modifiers "\('AKANE_CITY_STAGE_CAMPUS_DOUBLE_ADJACENCY', 'MODIFIER_CITY_DISTRICTS_ADJUST_YIELD_MODIFIER', 'AKANE_DISTRICT_IS_CAMPUS_AND_ADJ_LALALAI'\)" $failures 'Stage performance should use the official city-district yield modifier for Campus adjacency.'
Expect-Match $modifiers "\('AKANE_CITY_STAGE_COMMERCIAL_DOUBLE_ADJACENCY', 'MODIFIER_CITY_DISTRICTS_ADJUST_YIELD_MODIFIER', 'AKANE_DISTRICT_IS_COMMERCIAL_HUB_AND_ADJ_LALALAI'\)" $failures 'Stage performance should use the official city-district yield modifier for Commercial Hub adjacency.'
Expect-Match $modifiers "\('AKANE_CITY_STAGE_HOLY_SITE_DOUBLE_ADJACENCY', 'MODIFIER_CITY_DISTRICTS_ADJUST_YIELD_MODIFIER', 'AKANE_DISTRICT_IS_HOLY_SITE_AND_ADJ_LALALAI'\)" $failures 'Stage performance should use the official city-district yield modifier for Holy Site adjacency.'
Expect-Match $modifiers "\('AKANE_CITY_STAGE_LALALAI_CULTURE_BONUS', 'Amount', '100'\)" $failures 'Stage performance should double LALALAI culture by a 100% district yield modifier.'
Expect-Match $modifiers "\('AKANE_CITY_STAGE_CAMPUS_DOUBLE_ADJACENCY', 'Amount', '100'\)" $failures 'Stage performance should double Campus adjacency by a 100% district yield modifier.'
Expect-Match $modifiers 'AKANE_CITY_STAGE_LALALAI_BASE_CULTURE_COMPENSATION' $failures 'Stage performance should compensate for the LALALAI district''s flat base culture when doubling district yields.'
Expect-Match $modifiers "\('AKANE_CITY_STAGE_LALALAI_BASE_CULTURE_COMPENSATION', 'Amount', '-1'\)" $failures 'Stage performance should remove the extra copied base culture from the LALALAI district.'
Expect-NotMatch $modifiers "AKANE_CITY_STAGE_[A-Z_]+', 'Amount', '0\\.5'" $failures 'Stage performance should no longer rely on unsupported half-step district yield modifiers.'
Expect-NotMatch $modifiers "AKANE_CITY_STAGE_[A-Z_]+', 'Amount', '-0\\.5'" $failures 'Stage performance cleanup should no longer rely on unsupported half-step district yield modifiers.'
Expect-Match $modifiers 'AKANE_CITY_STAGE_AMPHITHEATER_TOURISM_ALL' $failures 'Stage performance should define city-wide Amphitheater tourism scaling.'
Expect-Match $modifiers 'AKANE_CITY_STAGE_ART_MUSEUM_TOURISM_ALL' $failures 'Stage performance should define city-wide Art Museum tourism scaling.'
Expect-Match $modifiers 'AKANE_CITY_STAGE_ARCHAEOLOGICAL_MUSEUM_TOURISM_ALL' $failures 'Stage performance should define city-wide Archaeological Museum tourism scaling.'
Expect-Match $modifiers 'AKANE_CITY_STAGE_BROADCAST_CENTER_TOURISM_ALL' $failures 'Stage performance should define city-wide Broadcast Center tourism scaling.'

Expect-NotMatch $gameplay 'MODIFIER_CITY_STAGE_LEGACY_CULTURE' $failures 'Gameplay stage rewards should no longer grant flat permanent city culture.'
Expect-Match $gameplay 'AttachStageAdjacencyModifiers' $failures 'Gameplay should attach permanent stage adjacency modifiers once per city.'
Expect-Match $gameplay 'PROPERTY_CITY_STAGE_REWARD_MODIFIERS_ATTACHED' $failures 'Gameplay should track whether stage reward modifiers were already attached.'
Expect-Match $gameplay 'PROPERTY_CITY_STAGE_ADJACENCY_MODIFIERS_ATTACHED' $failures 'Gameplay should track whether adjacency-doubling modifiers were already attached.'
Expect-NotMatch $gameplay 'GetDistrictAdjacencyHalfSteps' $failures 'Gameplay should no longer recompute district adjacency half-steps in Lua.'
Expect-NotMatch $gameplay 'ReconcileCityModifierHalfSteps' $failures 'Gameplay should no longer stack temporary half-step district modifiers.'

Complete-Test $failures 'Stage system verification passed.'
