$ErrorActionPreference = 'Stop'
. "$PSScriptRoot/TestHelpers.ps1"

$modifiers = Get-TestContent 'Data\Akane_Modifiers.sql'
$modeSystem = Get-TestContent 'Scripts\Akane_ModeSystem.lua'
$failures = New-FailureList

Expect-NotMatch $modifiers 'AKANE_CAMPUS_SCIENCE_FROM_ADJACENT_LALALAI' $failures 'Reasoning Master should no longer grant flat Campus science adjacency.'
Expect-NotMatch $modifiers 'AKANE_CITY_ATTACH_REASONING_SCIENCE_FROM_LIBRARY' $failures 'Reasoning Master should no longer add a Library-stage science bonus.'
Expect-NotMatch $modifiers 'AKANE_CITY_ATTACH_REASONING_SCIENCE_FROM_UNIVERSITY' $failures 'Reasoning Master should no longer add a University-stage science bonus.'
Expect-NotMatch $modifiers 'AKANE_CITY_ATTACH_REASONING_SCIENCE_FROM_RESEARCH_LAB' $failures 'Reasoning Master should no longer add a Research Lab-stage science bonus.'
Expect-NotMatch $modifiers 'AKANE_CITY_REASONING_SCIENCE_FROM_LIBRARY' $failures 'Library-stage science bonus definition should be removed.'
Expect-NotMatch $modifiers 'AKANE_CITY_REASONING_SCIENCE_FROM_UNIVERSITY' $failures 'University-stage science bonus definition should be removed.'
Expect-NotMatch $modifiers 'AKANE_CITY_REASONING_SCIENCE_FROM_RESEARCH_LAB' $failures 'Research Lab-stage science bonus definition should be removed.'
Expect-Match $modifiers "\('AKANE_LEADER_REASONING_SCIENCE_PERCENT', 'Amount', '10'\)" $failures 'Mathematics bonus should remain +10% science.'
Expect-Match $modifiers "\('AKANE_LEADER_REASONING_SCIENCE_THEORY_PERCENT', 'Amount', '10'\)" $failures 'Scientific Theory bonus should now be +10% science.'
Expect-Match $modifiers "\('AKANE_LEADER_REASONING_CULTURE_FLAT', 'MODIFIER_PLAYER_ADJUST_YIELD_CHANGE', NULL\)" $failures 'Reasoning Master flat culture should be attached at the player level.'
Expect-NotMatch $modifiers "\('AKANE_LEADER_REASONING_CULTURE_FLAT', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_CHANGE', NULL\)" $failures 'Reasoning Master flat culture should no longer be applied to every city.'

Expect-Match $modifiers "\('AKANE_MODE_AI_FAITH_FLAT', 'MODIFIER_PLAYER_ADJUST_YIELD_CHANGE', NULL\)" $failures 'Ai mode flat faith should be attached at the player level.'
Expect-Match $modifiers "\('AKANE_MODE_ACTOR_CULTURE_FLAT', 'MODIFIER_PLAYER_ADJUST_YIELD_CHANGE', NULL\)" $failures 'Actor mode flat culture should be attached at the player level.'
Expect-Match $modifiers "\('AKANE_MODE_WARRIOR_PRODUCTION_FLAT', 'MODIFIER_PLAYER_ADJUST_YIELD_CHANGE', NULL\)" $failures 'Ruby mode flat production should be attached at the player level.'
Expect-Match $modifiers "\('AKANE_MODE_AI_FAITH_FLAT_NEGATIVE', 'MODIFIER_PLAYER_ADJUST_YIELD_CHANGE', NULL\)" $failures 'Ai mode cleanup faith modifier should be attached at the player level.'
Expect-Match $modifiers "\('AKANE_MODE_ACTOR_CULTURE_FLAT_NEGATIVE', 'MODIFIER_PLAYER_ADJUST_YIELD_CHANGE', NULL\)" $failures 'Actor mode cleanup culture modifier should be attached at the player level.'
Expect-Match $modifiers "\('AKANE_MODE_WARRIOR_PRODUCTION_FLAT_NEGATIVE', 'MODIFIER_PLAYER_ADJUST_YIELD_CHANGE', NULL\)" $failures 'Ruby mode cleanup production modifier should be attached at the player level.'
Expect-NotMatch $modifiers "\('AKANE_MODE_AI_FAITH_FLAT', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_CHANGE', NULL\)" $failures 'Ai mode flat faith should no longer be applied to every city.'
Expect-NotMatch $modifiers "\('AKANE_MODE_ACTOR_CULTURE_FLAT', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_CHANGE', NULL\)" $failures 'Actor mode flat culture should no longer be applied to every city.'
Expect-NotMatch $modifiers "\('AKANE_MODE_WARRIOR_PRODUCTION_FLAT', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_CHANGE', NULL\)" $failures 'Ruby mode flat production should no longer be applied to every city.'

Expect-Match $modifiers "\('AKANE_MODE_AI_PROPHET_POINTS', 'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS', NULL\)" $failures 'Ai mode flat Prophet points should be attached at the player level.'
Expect-Match $modifiers "\('AKANE_MODE_AI_PROPHET_POINTS_PER_HOLY_SITE', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_GREAT_PERSON_POINTS', 'DISTRICT_IS_HOLY_SITE'\)" $failures 'Ai mode per-Holy-Site Prophet points should be bound to Holy Site districts.'
Expect-Match $modifiers "\('AKANE_MODE_ACTOR_ARTIST_POINTS_FLAT', 'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS', NULL\)" $failures 'Actor mode flat Artist points should be attached at the player level.'
Expect-Match $modifiers "\('AKANE_MODE_ACTOR_WRITER_POINTS_FLAT', 'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS', NULL\)" $failures 'Actor mode flat Writer points should be attached at the player level.'
Expect-Match $modifiers "\('AKANE_MODE_ACTOR_MUSICIAN_POINTS_FLAT', 'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS', NULL\)" $failures 'Actor mode flat Musician points should be attached at the player level.'
Expect-Match $modifiers "\('AKANE_MODE_ACTOR_ARTIST_POINTS', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_GREAT_PERSON_POINTS', 'DISTRICT_IS_LALALAI'\)" $failures 'Actor mode per-district Artist points should be bound to LALALAI districts.'
Expect-Match $modifiers "\('AKANE_MODE_ACTOR_WRITER_POINTS', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_GREAT_PERSON_POINTS', 'DISTRICT_IS_LALALAI'\)" $failures 'Actor mode per-district Writer points should be bound to LALALAI districts.'
Expect-Match $modifiers "\('AKANE_MODE_ACTOR_MUSICIAN_POINTS', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_GREAT_PERSON_POINTS', 'DISTRICT_IS_LALALAI'\)" $failures 'Actor mode per-district Musician points should be bound to LALALAI districts.'
Expect-Match $modifiers "\('AKANE_MODE_WARRIOR_GENERAL_POINTS', 'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS', NULL\)" $failures 'Ruby mode flat General points should be attached at the player level.'
Expect-Match $modifiers "\('AKANE_MODE_WARRIOR_GENERAL_POINTS_PER_ENCAMPMENT', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_GREAT_PERSON_POINTS', 'DISTRICT_IS_ENCAMPMENT'\)" $failures 'Ruby mode per-Encampment General points should be bound to Encampment districts.'

Expect-Match $modeSystem 'AKANE_MODE_ACTOR_WRITER_POINTS' $failures 'Actor mode positive modifier list should include Great Writer points.'
Expect-Match $modeSystem 'AKANE_MODE_ACTOR_WRITER_POINTS_FLAT' $failures 'Actor mode positive modifier list should include flat Great Writer points.'
Expect-Match $modeSystem 'AKANE_MODE_ACTOR_MUSICIAN_POINTS' $failures 'Actor mode positive modifier list should include Great Musician points.'
Expect-Match $modeSystem 'AKANE_MODE_ACTOR_MUSICIAN_POINTS_FLAT' $failures 'Actor mode positive modifier list should include flat Great Musician points.'
Expect-Match $modeSystem 'AKANE_MODE_ACTOR_WRITER_POINTS_NEGATIVE' $failures 'Actor mode negative modifier list should include Great Writer cleanup.'
Expect-Match $modeSystem 'AKANE_MODE_ACTOR_WRITER_POINTS_FLAT_NEGATIVE' $failures 'Actor mode negative modifier list should include flat Great Writer cleanup.'
Expect-Match $modeSystem 'AKANE_MODE_ACTOR_MUSICIAN_POINTS_NEGATIVE' $failures 'Actor mode negative modifier list should include Great Musician cleanup.'
Expect-Match $modeSystem 'AKANE_MODE_ACTOR_MUSICIAN_POINTS_FLAT_NEGATIVE' $failures 'Actor mode negative modifier list should include flat Great Musician cleanup.'
Expect-Match $modeSystem 'AKANE_MODE_AI_PROPHET_POINTS' $failures 'Ai mode positive modifier list should include flat Prophet points.'
Expect-Match $modeSystem 'AKANE_MODE_AI_PROPHET_POINTS_PER_HOLY_SITE' $failures 'Ai mode positive modifier list should include per-Holy-Site Prophet points.'
Expect-Match $modeSystem 'AKANE_MODE_WARRIOR_GENERAL_POINTS' $failures 'Ruby mode positive modifier list should include flat General points.'
Expect-Match $modeSystem 'AKANE_MODE_WARRIOR_GENERAL_POINTS_PER_ENCAMPMENT' $failures 'Ruby mode positive modifier list should include per-Encampment General points.'

Complete-Test $failures 'Modifier scope verification passed.'
