$ErrorActionPreference = 'Stop'
. "$PSScriptRoot/TestHelpers.ps1"

$textZh = Get-TestContent 'Text\Akane_Text_zh_Hans_CN.xml'
$textEn = Get-TestContent 'Text\Akane_Text_en_US.xml'
$gameplay = Get-TestContent 'Scripts\Akane_Gameplay.lua'
$failures = New-FailureList

Expect-Match $gameplay 'UnitGreatPersonCreated' $failures 'Great Person recruitment should still trigger a mode reward hook.'
Expect-Match $gameplay 'UnitGreatPersonActivated' $failures 'Great Person retirement should still trigger a leader reward hook.'
Expect-Match $gameplay 'CityMadePurchase' $failures 'Ai mode should still trigger on city purchases.'
Expect-Match $gameplay 'FaithChanged' $failures 'Ai mode should still watch faith balance changes.'
Expect-Match $gameplay 'ChangeGoldBalance' $failures 'Ai mode faith purchases should still refund gold.'
Expect-Match $gameplay 'LOC_AKANE_MODE_ACTOR_INSPIRATION_WORLD_TEXT' $failures 'Actor mode should use its own Inspiration world text.'
Expect-Match $gameplay 'LOC_AKANE_REASONING_EUREKA_WORLD_TEXT' $failures 'Reasoning Master should use its own Eureka world text.'
Expect-NotMatch $gameplay 'LOC_AKANE_MODE_AI_INSPIRATION_WORLD_TEXT' $failures 'Ai mode should no longer use the Great Person Inspiration world text.'
Expect-NotMatch $gameplay 'LOC_AKANE_MODE_ACTOR_EUREKA_WORLD_TEXT' $failures 'Actor mode should no longer use the Great Person Eureka world text.'

Expect-Match $textZh 'LOC_TRAIT_LEADER_KUROKAWA_AKANE_DESCRIPTION' $failures 'Chinese leader text row should exist.'
Expect-Match $textZh 'LOC_UNIT_STAGE_ACTOR_DESCRIPTION' $failures 'Chinese stage actor description row should exist.'
Expect-Match $textZh 'LOC_AKANE_STAGE_ACTOR_PERFORM_TOOLTIP' $failures 'Chinese stage actor tooltip row should exist.'
Expect-Match $textZh 'LOC_AKANE_MODE_AI_TOOLTIP' $failures 'Chinese Ai mode tooltip row should exist.'
Expect-Match $textZh 'LOC_AKANE_MODE_ACTOR_INSPIRATION_WORLD_TEXT' $failures 'Chinese Actor Inspiration world text row should exist.'
Expect-Match $textZh 'LOC_AKANE_REASONING_EUREKA_WORLD_TEXT' $failures 'Chinese Reasoning Master Eureka world text row should exist.'

Expect-Match $textEn '\+1 \[ICON_Culture\] Culture' $failures 'English leader text should mention the new +1 culture bonus.'
Expect-NotMatch $textEn 'Libraries, Universities, and Research Labs' $failures 'English leader text should no longer mention the Campus building science chain.'
Expect-Match $textEn 'Great Person retirement grants a random Eureka' $failures 'English leader text should mention the Reasoning Master Eureka reward.'
Expect-Match $textEn 'Scientific Theory' $failures 'English leader text should still mention Scientific Theory.'
Expect-Match $textEn '\+16% to all yields' $failures 'English text should mention the updated switch buff.'
Expect-Match $textEn '\+30% Tourism' $failures 'English stage actor text should mention the tourism boost.'
Expect-Match $textEn 'Faith-purchased units and buildings refund 80%' $failures 'English Ai mode tooltip should still mention the faith purchase gold refund.'
Expect-NotMatch $textEn 'Hoshino Ai.*recruiting a Great Person grants a random Inspiration' $failures 'English Ai mode tooltip should no longer mention Great Person Inspiration.'
Expect-Match $textEn 'Sayahime.*recruiting a Great Person grants a random Inspiration' $failures 'English Actor mode tooltip should mention Great Person Inspiration.'
Expect-NotMatch $textEn 'Sayahime.*Great Person retirement also grants a random Eureka' $failures 'English Actor mode tooltip should no longer mention Great Person Eureka.'
Expect-Match $textEn 'Great Writer' $failures 'English Actor mode tooltip should mention Great Writer points.'
Expect-Match $textEn 'Great Musician points' $failures 'English Actor mode tooltip should mention Great Musician points.'
Expect-Match $textEn 'Commercial Hubs and Harbors gain \+2 \[ICON_Gold\] Gold' $failures 'English district text should mention +2 gold for Commercial Hubs and Harbors.'
Expect-Match $textEn 'Entertainment Complexes and Water Parks gain \+2 \[ICON_Production\] Production' $failures 'English district text should mention +2 production for Entertainment Complexes and Water Parks.'
Expect-Match $textEn 'Entertainment Complexes, Water Parks,' $failures 'English stage actor tooltip should include Entertainment Complexes and Water Parks in doubled adjacency.'
Expect-Match $textEn 'defeating enemy units grants' $failures 'English text should mention Ruby mode''s faith-on-kill reward.'
Expect-Match $textEn '80%[^<]*Faith' $failures 'English text should mention the 80% faith reward amount.'
Expect-NotMatch $textEn 'will boosts' $failures 'English civilization text should no longer contain the broken grammar in the LALALAI trait description.'
Expect-Match $textEn 'Industrial Zones' $failures 'English civilization text should mention Industrial Zones in the building-yield chain.'
Expect-Match $textEn 'player-wide flat \+1 \[ICON_Culture\] Culture' $failures 'English leader text should clarify the flat culture bonus is player-wide.'
Expect-Match $textEn 'permanently have their adjacency yields doubled' $failures 'English stage actor text should clarify the adjacency boost is permanent.'
Expect-Match $textEn 'player-wide flat \+1 \[ICON_Faith\] Faith' $failures 'English Ai mode tooltip should clarify the flat faith bonus is player-wide.'
Expect-Match $textEn 'player-wide flat \+1 \[ICON_Production\] Production' $failures 'English Ruby mode tooltip should clarify the flat production bonus is player-wide.'

Complete-Test $failures 'Text and documentation verification passed.'
